# .github/workflows/sync-content.yml
name: Sync Content from Google Sheets

on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/sync-content.yml'
      - 'scripts/sync-content.js'

jobs:
  sync-content:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Create package.json for ES modules
        run: |
          echo '{"type": "module"}' > package.json
      
      - name: Install dependencies
        run: |
          npm install google-spreadsheet google-auth-library
      
      - name: Sync content from Google Sheets
        env:
          GOOGLE_SHEETS_ID: ${{ secrets.GOOGLE_SHEETS_ID }}
          GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
        run: node scripts/sync-content.js
      
      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/data/
          git commit -m "🔄 Auto-sync content from Google Sheets"
          git push
